server:
  port: 10010
spring:
  application:
    name: generator-web
  datasource:
    url: jdbc:mysql://192.168.164.52:3306/epinbao_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false # 配置的缓存的全局开关
    lazyLoadingEnabled: false # 延时加载的开关
    multipleResultSetsEnabled: false # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    default-executor-type: reuse
